---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m0s
  provider: generic
  ref:
    tag: local
  url: oci://registry.my.labs/flux/podinfo-kustomize
