---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m0s
  provider: generic
  ref:
    tag: 6.5.3
  url: oci://registry.my.labs/gitops/podinfo
  certSecretRef:
    name: labs-root-ca
  verify:
    provider: cosign
    secretRef:
      name: cosign-pub