---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  chart:
    spec:
      sourceRef:
        kind: GitRepository
        name: podinfo
      chart: ./charts/podinfo
      reconcileStrategy: Revision
  interval: 1m0s
  targetNamespace: podinfo-helm
  values:
    ui:
      color: "#808080"
      message: "Podinfo Helm"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: ca-issuer
        external-dns.alpha.kubernetes.io/hostname: &host podinfo-helm.my.labs
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
        - host: *host
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: ingress-tls