---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: podinfo
    namespace: flux-system
  path: ./kustomize
  prune: true
  interval: 1m0s
  targetNamespace: podinfo-kustomize
  postBuild:
    substitute:
      host: "podinfo-kustomize.my.labs"
      podinfo_ui_color: "\"#000000\""
      podinfo_ui_message: "Podinfo Kustomize"