---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  url: ssh://git@gitlab.my.labs/labs-group/labs-project.git
  secretRef:
    name: gitlab-auth
  ref:
    branch: main
  interval: 1m0s
